version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: real_estate
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  nextjs:
    build: .
    container_name: nextjs
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql

volumes:
  mysql_data:
